// This file is generated by scripts/generate-bindings.mjs.

// Do not edit it manually; edit the Rust command models instead.



export interface ConfigData {
  processes_update_time: number;
  processes_body_background_color: string;
  processes_body_color: string;
  processes_head_background_color: string;
  processes_head_color: string;
  processes_table_values: string[];
  processes_border_color: string;
  processes_tree_toggle_color: string;
  processes_monitor_border_color: string;
  processes_services_active_color: string;
  processes_services_inactive_color: string;
  processes_services_failed_color: string;
  processes_services_transitioning_color: string;
  performance_update_time: number;
  performance_sidebar_background_color: string;
  performance_sidebar_color: string;
  performance_sidebar_selected_color: string;
  performance_background_color: string;
  performance_title_color: string;
  performance_label_color: string;
  performance_value_color: string;
  performance_graph_color: string;
  performance_sec_graph_color: string;
  performance_scrollbar_color: string;
  sensors_update_time: number;
  sensors_background_color: string;
  sensors_foreground_color: string;
  sensors_boxes_background_color: string;
  sensors_boxes_foreground_color: string;
  sensors_battery_background_color: string;
  sensors_battery_frame_color: string;
  sensors_boxes_title_foreground_color: string;
  sensors_battery_case_color: string;
  sensors_hidden_ids: string[];
  sensors_label_overrides: string;
  sensors_warning_thresholds: string;
  sensors_critical_thresholds: string;
  sensors_graph_color: string;
  sensors_status_ok_color: string;
  sensors_status_warning_color: string;
  sensors_status_critical_color: string;
  disks_update_time: number;
  disks_background_color: string;
  disks_boxes_background_color: string;
  disks_name_foreground_color: string;
  disks_size_foreground_color: string;
  disks_partition_background_color: string;
  disks_partition_usage_background_color: string;
  disks_partition_name_foreground_color: string;
  disks_partition_type_foreground_color: string;
  disks_partition_usage_foreground_color: string;
  disks_smart_ok_color: string;
  disks_smart_fail_color: string;
  disks_smart_warning_color: string;
  navbar_background_color: string;
  navbar_buttons_background_color: string;
  navbar_buttons_foreground_color: string;
  navbar_search_background_color: string;
  navbar_search_foreground_color: string;
  heatbar_color_one: string;
  heatbar_color_two: string;
  heatbar_color_three: string;
  heatbar_color_four: string;
  heatbar_color_five: string;
  heatbar_color_six: string;
  heatbar_color_seven: string;
  heatbar_color_eight: string;
  heatbar_color_nine: string;
  heatbar_color_ten: string;
  heatbar_background_color: string;
  config_background_color: string;
  config_container_background_color: string;
  config_input_background_color: string;
  config_input_border_color: string;
  config_button_background_color: string;
  config_button_foreground_color: string;
  config_text_color: string;
  language: string;
  show_virtual_interfaces: boolean;
}

export interface CpuInformations {
  name: string | null;
  socket: string | null;
  cores: string | null;
  threads: string | null;
  live_threads: string | null;
  usage: number | null;
  core_usages: number[] | null;
  current_speed: string | null;
  base_speed: string | null;
  max_speed: string | null;
  virtualization: string | null;
  virtual_machine: string | null;
  uptime: string | null;
  temperature: string | null;
  cache_l1: string | null;
  cache_l2: string | null;
  cache_l3: string | null;
}

export interface GpuInformations {
  id: string | null;
  name: string | null;
  driver_version: string | null;
  memory_total: string | null;
  memory_used: string | null;
  memory_free: string | null;
  temperature: string | null;
  utilization: string | null;
  clock_speed: string | null;
  wattage: string | null;
  fan_speed: string | null;
  performance_state: string | null;
}

export interface Memory {
  total: number | null;
  free: number | null;
  available: number | null;
  cached: number | null;
  active: number | null;
  swap_total: number | null;
  swap_cache: number | null;
}

export interface MemoryHardwareInfo {
  speed: string | null;
  slots_used: string | null;
  form_factor: string | null;
  memory_type: string | null;
}

export interface Network {
  interface: string;
  upload: number;
  download: number;
  total_upload: number;
  total_download: number;
  mac_address: string | null;
  ipv4_addresses: string[];
  ipv6_addresses: string[];
  link_speed_mbps: number | null;
  connection_state: string;
  interface_type: string;
  wifi_signal_percent: number | null;
  wifi_signal_dbm: number | null;
  rx_errors: number;
  tx_errors: number;
  rx_dropped: number;
  tx_dropped: number;
}

export interface NetworkInterface {
  interface: string;
  mac_address: string | null;
  ipv4_addresses: string[];
  ipv6_addresses: string[];
  link_speed_mbps: number | null;
  connection_state: string;
  interface_type: string;
  wifi_signal_percent: number | null;
  wifi_signal_dbm: number | null;
  rx_errors: number;
  tx_errors: number;
  rx_dropped: number;
  tx_dropped: number;
}

export interface Process {
  pid: number;
  start_time: number;
  name: string | null;
  ppid: number | null;
  state: string | null;
  user: string | null;
  memory: string | null;
  cpu_usage: string | null;
  read_disk_usage: string | null;
  write_disk_usage: string | null;
  read_disk_speed: string | null;
  write_disk_speed: string | null;
}

export interface SystemService {
  name: string;
  description: string;
  load_state: string;
  active_state: string;
  sub_state: string;
  unit_file_state: string;
}

export interface ServiceDetails {
  name: string;
  unit_file_path: string | null;
  status: string;
  logs: string;
}

export interface SmartAttribute {
  id: number;
  name: string;
  current: number;
  worst: number;
  threshold: number;
  raw: number;
  raw_string: string;
  pre_failure: boolean;
  failed: boolean;
}

export interface AtaSmartData {
  overall_health: boolean;
  attributes: SmartAttribute[];
  power_on_hours: number | null;
  temperature_celsius: number | null;
  reallocated_sectors: number | null;
  pending_sectors: number | null;
  uncorrectable_sectors: number | null;
}

export interface NvmeSmartData {
  overall_health: boolean;
  critical_warning: number;
  temperature_celsius: number | null;
  available_spare_percent: number;
  available_spare_threshold: number;
  percentage_used: number;
  power_on_hours: number | null;
  power_cycles: number | null;
  unsafe_shutdowns: number | null;
  media_errors: number | null;
  data_units_read_gb: number | null;
  data_units_written_gb: number | null;
  limited: boolean;
}

export interface Partition {
  name: string;
  dev_path: string;
  major: number;
  minor: number;
  size: number;
  partition_number: number | null;
  partuuid: string | null;
  start_sector: number | null;
  read_only: boolean | null;
  alignment_offset: number | null;
  discard_alignment: number | null;
  holders: string[];
  available_space: number | null;
  total_space: number | null;
  used_space: number | null;
  file_system: string | null;
  mount_point: string | null;
}

export interface Disk {
  name: string;
  dev_path: string;
  major: number;
  minor: number;
  sysfs_path: string | null;
  model: string | null;
  vendor: string | null;
  serial: string | null;
  firmware_rev: string | null;
  wwid: string | null;
  transport: string | null;
  device_state: string | null;
  size: number;
  partitions: Partition[];
  rotational: boolean;
  physical_block_size: number;
  logical_block_size: number;
  removable: boolean;
  read_only: boolean;
  trim_supported: boolean;
  scheduler: string | null;
  active_scheduler: string | null;
  available_schedulers: string[];
  write_cache: string | null;
  queue_depth: number | null;
  read_ahead_kb: number | null;
  max_sectors_kb: number | null;
  max_hw_sectors_kb: number | null;
  minimum_io_size: number | null;
  optimal_io_size: number | null;
  discard_granularity: number | null;
  discard_max_bytes: number | null;
  discard_zeroes_data: boolean | null;
  fua: boolean | null;
  dax: boolean | null;
  zoned: string | null;
  nr_zones: number | null;
  numa_node: number | null;
  queue_count: number | null;
  controller_id: string | null;
  controller_address: string | null;
  subsystem_nqn: string | null;
  holders: string[];
  slaves: string[];
  read_speed: string;
  write_speed: string;
  read_iops: string;
  write_iops: string;
  io_busy_percent: string;
  total_read: number;
  total_write: number;
  total_discarded: number;
  total_reads: number;
  total_writes: number;
  total_discards: number;
  total_flushes: number;
  io_in_progress: number;
  io_time_ms: number;
  weighted_io_time_ms: number;
}

export interface BatteryData {
  model: string | null;
  state: string;
  cycle_count: number | null;
  energy: number;
  time_to_full: number | null;
  technology: string;
  time_to_empty: number | null;
  temperature: number | null;
  state_of_health: number;
  percentage: number;
}

export interface SensorData {
  id: string;
  name: string;
  value: number;
  warning: number | null;
  critical: number | null;
  sensor_type: string;
  unit: string;
}

export interface HwMonData {
  index: number;
  name: string;
  sensors: SensorData[];
}

export interface TotalUsage {
  memory: number | null;
  cpu: number | null;
  processes: number | null;
}

export type SmartData = ({ type: "Ata" } & AtaSmartData) | ({ type: "Nvme" } & NvmeSmartData);

export type CpuData = CpuInformations;

export type GpuData = GpuInformations;

export type MemoryUsage = Memory;

export type NetworkUsage = Network;

export type DiskData = Disk;

export type PartitionData = Partition;

export type TotalUsages = TotalUsage;
